### ISSUE TITLE
new inscriptions not indexing apparently? 

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip#110]
beth0153: I made an edit ( -/- changed to <lb break='no"/> ) then I committed it and then I ran the Process single inscription script. 
The correct xml file is showing up on the "View XML" view, 
However, the display still shows the -/- and no line break.

Not sure if this is single inscription processing isn't working or if there is an issue with the indexing.

**Comment by birkin** [comment]
don't know what the problem was but new inscriptions are now indexing.
