### ISSUE TITLE
Things for a reindex

### ISSUE THREAD

**Issue by crotger** [Brown-University-Library/iip#127]
Schema:
Change notBefore and notAfter to DateFields, instead of StrFields
Make place searching not tokenized
Rethink region/settlement indexing
Default values for null fields
Consider indexing more fields

XSL:
Break physical type over spaces
Deal with whitespace issues on `<choice><abbr></abbr><expan></expan></choice>` elements (caes0012)
Deal with `<hi rend=...>` elements

**Comment by crotger** [comment]
Schema:
Add hasImage or imageLinks field

On Index: check for corresponding image data

**Comment by crotger** [comment]
XSL: more strange bracket behavior as in hamm0001

**Comment by emylonas** [comment]
places handled differently - will have (EM check details) up to 3 kind of place info:

original location  &lt;originLoc> ? 
find spot   &lt;provenance>
curent location  &lt;currentLoc

the first two will likely have location info. the third may be just a museum id

**Comment by emylonas** [comment]
em to add info for coordinates to geo elements

**Comment by emylonas** [comment]
handle multi valued attributes correctly ( genre, material, object)

**Comment by emylonas** [comment]
done
