### ISSUE TITLE
facets with no values showing up on dev, not prod

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip#137]
@birkin just pulled and deployed on worfdev a change that @crotger made to IIP so that menu facets don't display if there are not inscriptions that correspond to them. This should get rid of ghost entries. However, this doesn't seem to be having an effect on worfdev, perhaps because it is indexing a different set of inscriptions. The XML view (which just goes to a set of inscriptions on disk) shows the correct inscriptions. Also there are changes at odd times. I wonder if there is a cron job that we have forgotten about. In any case, it woulg be good to figure out 
a) how to make ghost entries go away.
b) exactly what we are indexing and when. 

For ex. on worfdev, in the places menu, there is an entry Ioppe (Jaffa) but if you select it, there are no corresponding inscriptions. So it's not being removed from the menu, even though there are 0 instances.

**Comment by crotger** [comment]
That is super strange. I looked at the worfdev index just now, and the Ioppe (Jaffa) entry isn't even in there before filtering out the 0-count entries (http://worfdev.services.brown.edu:8082/solr/iip_inscriptions/select?q=*%3A*&rows=0&wt=json&indent=true&facet=true&facet.field=placeMenu&facet.limit=-1). 

It definitely still is in the place selector on http://worfdev.services.brown.edu/cds/projects/iip/search/ , though.... I think something else is going on here.

**Comment by emylonas** [comment]
this is the same as #125 
Fixed by making menus less persistent. @birkin can expand details.
