### ISSUE TITLE
msItem/@class not indexing multiple attribute values correctly

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip#138]
Inscriptions with `<msItem class="#funerary #financial" ana="jewish">`
shows up in the Search menu as _funerary financial_
it should show up under _funerary_ and under _financial_

an example is jeru0206.xml

I think religion does it properly

**Comment by crotger** [comment]
Note for self: msItem's class attribute goes into the 'type' field in solr. we can copy the field type from the usep schema for these sorts of attrs and use it here to break these into multiple values on index. This will be a schema upgrade and a reindex.

**Comment by crotger** [comment]
solved with a reindex on worfdev
