### ISSUE TITLE
Solr not updating some files

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip#141]
've been checking the IIP problem inscriptions - i also looked at some of the logs. The problems I've located are all cases where there was a bad inscription ID which was also reflected in file name, or where the file name and the file id didn't match. 
ID                 filename
masa0567   Masa0567
masa0773   Masa 0773
masa0774   Masa 0774
masa0775   Masa 0775

the id and filename should be identical now, but solr still thinks it's the other name. It indexes things fine, but in the case of masa0567, it won't display the XML as its looking for Masa0567

in the case of masa0773, 4, 5 I can see the file in the search results, but the little down arrow that expands the result doesn't work. 

You can see the problem by searching for "masa" in the Description/Place ID box, and also making sure to select all proofreading statuses.

It's the first 4 inscriptions. for the first 3, try clicking the little down arrows. No dice

For masa0567, go to Full inscription and select View XML

**Comment by emylonas** [comment]
do you think I could fix it by deleting the offending inscriptions, reindexing and then adding them back in?

**Comment by emylonas** [comment]
I've deleted the 4 files listed above, recommitted to svn then done an "index all" and then a "delete orphans" The files are gone from the server (if you try to look at the xml, it's not there) and they are gone from solr (look on tuvok, search for "inscription_id:masa077*" and they are not there. 

But they are not gone from the site. They show up when you search for "masa" and they are at the top, because they are still being called by their incorrect inscription_id field. 

This looks like a caching or django problem. We had the same thing a while ago when we were trying to make values in the search boxes disappear when the files changed. This is discussed in #125 and #137 . Apparently Birkin did something to get rid of cached or persistent values. I don't know if it was in solr or django. 

Does anyone remember?

**Comment by birkin** [comment]
- Looking into this, I'm focusing on 'masa0567' and 'Masa0567' for now.
- As I understand it, [this Masa0567](http://library.brown.edu/cds/projects/iip/viewinscr_zotero/Masa0567/) entry should not exist, but [this masa0567](http://library.brown.edu/cds/projects/iip/viewinscr_zotero/masa0567/) entry is ok.

**Comment by emylonas** [comment]
repeat of email just sent. Yes, I tried committing a version of the files that had no masa0567 at all. and reindexing. it didnt' disappear. 

the file doesn't exist. There is no file Masa0567.xml

**Comment by birkin** [comment]
I believe I see the issue: delete-orphans is failing; am on the case.

**Comment by emylonas** [comment]
makes sense - I tried clicking it, but it didn't want to work.

**Comment by crotger** [comment]
ids are picked up from the `<idno>` element, `/TEI/teiHeader/fileDesc/publicationStmt/idno/@xml:id` . see https://github.com/Brown-University-Library/usep-data/blob/master/resources/xsl/USEp_to_Solr.xsl#L175

if there's somewhere else we could get them to avoid typos, let me know.

**Comment by crotger** [comment]
wow, sorry, wrong project, but there's a similar line in the XSL that makes IIP docs

**Comment by birkin** [comment]
E.M., I think this is fixed; check when you have a chance (and close if all's well).

For reference, the delete-orphans command needed a fixes:
- https://github.com/Brown-University-Library/iip/commit/8e2b3247349ad03ea7d6de4fa48b9b53166c1ff2
- https://github.com/Brown-University-Library/iip/commit/68f50fd7b0c781b5e451786fb152f4bd53af6d48

**Comment by emylonas** [comment]
The phantom inscriptions are gone - I'm can't test delete orphans at this point - I ran it, but don't know if Birkin had already run it.
