### ISSUE TITLE
Sort facet lists by label, not xml:id

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip#143]
For genre, object, sort the lists by label, unless there is no xml:id at all, in which case, sort by value.

**Comment by crotger** [comment]
Note for self: can use another bit of USEp code here https://github.com/Brown-University-Library/usepweb_project/blob/master/usep_app/templatetags/vocab.py , sort from frontend using a django tag

**Comment by crotger** [comment]
taken care of in #145
