### ISSUE TITLE
Names of facets in the search results list

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip#149]
Currently these read: 
CITY
LANGUAGE
REGION
RELIGION
PHYSICAL TYPE
TYPE

can we change 
PHYSICAL TYPE to OBJECT
TYPE to GENRE

and change the order
LANGUAGE
GENRE
OBJECT
REGION
CITY
RELIGION

**Comment by crotger** [comment]
addressed in recent pr #151
