### ISSUE TITLE
display: masa0796 has sub divs...

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip#155]
not sure how this should display. There is a textpart with the label a and one iwth the label  b. I think they are the front and back of the jug. We should show the difference and not display sequentially. 

possibly a label or division 
part a

part b

@GaiaLembi, what do you think?

**Comment by GaiaLembi** [comment]
If we could fit front and back into a single xml file, that would be great.
There are a few a/b instances, but I cannot remember them by heart.

**Comment by crotger** [comment]
Does this look okay? 
<img width="272" alt="screen shot 2017-03-21 at 12 28 56 pm" src="https://cloud.githubusercontent.com/assets/5515192/24158206/08928e6c-0e32-11e7-8e5f-89922618e605.png">

**Comment by GaiaLembi** [comment]
This looks fine to me.
Could we also write things like "recto" and "verso", instead of Part a/b?

**Comment by crotger** [comment]
of course! right now I'm just having it show whatever is in the "n" attribute of the `<div type="textpart" n="...">`, but we can discuss how this would be encoded.
